# Generated by Django 5.2 on 2025-04-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patient_bp_patient_oxygen_patient_patient_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bp',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='oxygen',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sugar',
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to=settings.AUTH_USER_MODEL),
        ),
    ]
